extends Node

class_name ListenerPlayerActions

enum ListenerPlayerActions {
	INDICATE_UP,
	INDICATE_UPPER_LEFT,
	INDICATE_UPPER_RIGHT,
	INDICATE_LEFT,
	INDICATE_RIGHT,
	INDICATE_DOWN,
	INDICATE_LOWER_LEFT,
	INDICATE_LOWER_RIGHT,
	NO_INDICATION
}
